# Generated by Django 5.1.7 on 2025-04-29 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_phone'),
        ('catalog', '0002_alter_album_format_color'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='applied_promocode',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='applied_promotion',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='customer',
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма покупки')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма покупок')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Накопительная скидка (%)')),
                ('albums', models.ManyToManyField(to='catalog.album')),
                ('applied_promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promocode')),
                ('applied_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_records', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.DeleteModel(
            name='CumulativeDiscount',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
