# Generated by Django 5.1.7 on 2025-04-30 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_purchasehistory_albums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная скидка (руб)'),
        ),
    ]
