# Generated by Django 5.1.7 on 2025-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление данных'),
        ),
    ]
