# Generated by Django 5.1.7 on 2025-05-22 01:31

import django.db.models.deletion
import utils.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название медианосителя')),
            ],
            options={
                'verbose_name': 'Медианоситель',
                'verbose_name_plural': 'Медианосители',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер прайс-листа')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.image_helpers.upload_function, verbose_name='Изображение')),
                ('use_in_slider', models.BooleanField(default=False, verbose_name='Использовать в слайдере')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея изображений',
                'verbose_name_plural': 'Галерея изображений',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название лейбла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Лейбл',
                'verbose_name_plural': 'Лейблы',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя музыканта')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия музыканта')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль в группе')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.image_helpers.upload_function)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель/группа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.image_helpers.upload_function)),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр')),
                ('members', models.ManyToManyField(blank=True, related_name='artist', to='catalog.member', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стиля')),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='catalog.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('tracklist', models.TextField(blank=True, null=True, verbose_name='Трэклист')),
                ('description', models.TextField(blank=True, default='Описание появится позже', null=True, verbose_name='Описание')),
                ('condition', models.CharField(blank=True, help_text='Например: Mint (идеальное), Near Mint (почти идеальное), Very Good (очень хорошее) и т.д.', max_length=50, null=True, verbose_name='Состояние товара')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Наличие на складе')),
                ('out_of_stock', models.BooleanField(default=False, editable=False, verbose_name='Нет в наличии')),
                ('offer_of_the_week', models.BooleanField(default=False, verbose_name='Предложение недели')),
                ('image', models.ImageField(upload_to=utils.image_helpers.upload_function)),
                ('slug', models.SlugField(blank=True, help_text='Оставьте пустым для автозаполнения')),
                ('format_quantity', models.CharField(blank=True, help_text='Примеры: "2xVinyl" (две виниловые пластинки), "1xCD" (один компакт-диск), "1xVinyl + 1xCD" (комбинированный набор)', max_length=100, null=True, verbose_name='Количество носителей')),
                ('format_type', models.CharField(blank=True, help_text='Пример: LP (Long Play - полноформатный альбом), SP (Single Play - сингл), EP (Extended Play - мини альбом)', max_length=100, null=True, verbose_name='Тип формата')),
                ('format_edition', models.CharField(blank=True, help_text='Пример: Reissue (переиздание), Expanded Edition (расширенное издание), Limited Edition (ограниченное издание)', max_length=100, null=True, verbose_name='Издание')),
                ('format_color', models.CharField(blank=True, help_text='Пример: White (белый), Black (чёрный), Transparent (прозрачный), Multicolor (многоцветный), или любой другой', max_length=100, null=True, verbose_name='Цвет носителя')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.artist', verbose_name='Исполнитель')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна выпуска')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.label', verbose_name='Лейбл')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mediatype', verbose_name='Тип медианосителя')),
                ('styles', models.ManyToManyField(blank=True, to='catalog.style', verbose_name='Стили')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.album', verbose_name='Альбом')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.pricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Позиция прайс-листа',
                'verbose_name_plural': 'Позиции прайс-листа',
                'unique_together': {('price_list', 'album')},
            },
        ),
    ]
