# Generated by Django 5.1.7 on 2025-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если цена не указана, будет использоваться цена из активного прайс-листа.', max_digits=10, null=True, verbose_name='Базовая цена'),
        ),
    ]
