# Generated by Django 5.1.7 on 2025-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='format_color',
            field=models.CharField(blank=True, help_text='Пример: White (белый), Black (чёрный), Transparent (прозрачный), Multicolor (многоцветный), или любой другой', max_length=100, null=True, verbose_name='Цвет носителя'),
        ),
    ]
