# Generated by Django 5.1.7 on 2025-03-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_album_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='slug',
        ),
    ]
