# Generated by Django 5.1.7 on 2025-04-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_products_alter_cartproduct_cart_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart', 'content_type', 'object_id')},
        ),
    ]
