# Generated by Django 5.1.7 on 2025-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartproduct_unique_together'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promocode', verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='cart',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оригинальная цена'),
        ),
    ]
