# Generated by Django 5.1.7 on 2025-03-29 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_date_remove_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='Платёжная система Stripe', max_length=50, null=True, verbose_name='Способ оплаты'),
        ),
    ]
