# Generated by Django 5.1.7 on 2025-04-27 13:17

import django.db.models.deletion
import django.utils.timezone
import utils.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartproduct_unique_together'),
        ('orders', '0003_alter_order_created_at_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Товар поврежден (царапины, дефекты)'), ('wrong', 'Неправильный альбом / исполнитель'), ('not_needed', 'Товар больше не нужен'), ('other', 'Другое')], max_length=50, verbose_name='Причина возврата')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Подробности')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.image_helpers.upload_function, verbose_name='Прикрепленный файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Заказ')),
                ('products', models.ManyToManyField(related_name='return_requests', to='cart.cartproduct', verbose_name='Товары для возврата')),
            ],
            options={
                'verbose_name': 'Заявка на возврат',
                'verbose_name_plural': 'Заявки на возврат',
            },
        ),
    ]
