# Generated by Django 5.1.7 on 2025-04-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0004_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='accounts.customer', verbose_name='Покупатель'),
        ),
    ]
