# Generated by Django 5.1.7 on 2025-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_returnrequest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('canceled', 'Отменена'), ('paid', 'Выплачена')], default='pending', max_length=20, verbose_name='Статус запроса'),
        ),
    ]
