# Generated by Django 5.1.7 on 2025-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Готов к выдаче'), ('completed', 'Заказ завершён')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Заявка одобрена'), ('canceled', 'Заявка отменена'), ('paid', 'Возврат выплачен')], default='pending', max_length=20, verbose_name='Статус запроса'),
        ),
    ]
